name: build-ci

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  Build_Push:
    runs-on: ubuntu-latest

    name: Build & Push to registry
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        run: |
          mvn clean package

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Push to S3
        run: |
          aws s3 cp target/spring-petclinic-2.4.0.BUILD-SNAPSHOT.jar s3://iac-demo-artifactory/

      - name: Push to ECR
